source 'https://rubygems.org'
git_source(:github) { |name| "https://github.com/#{name}.git" }

gem 'aasm', '~> 3.4.0'
gem 'actionpack', '>= 4.1.14.2'
gem 'activerecord', '>= 4.1.14.1'
gem 'activesupport', '>= 4.1.11'
gem 'active_hash'
gem 'acts-as-taggable-on'
gem 'amqp'
gem 'angularjs-rails', '1.3.15'
gem 'bcrypt'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'bootstrap-sass', '~> 3.4.1'
gem 'bootstrap-wysihtml5-rails', github: 'nerian/bootstrap-wysihtml5-rails'
gem 'bourbon'
gem 'browser'
gem 'bunny'
gem 'cancancan'
gem 'carrierwave'
gem 'certified'
gem 'clipboard-rails'
gem 'coffee-rails', '~> 4.2', '>= 4.2.2'
gem 'country_select'
gem 'daemons-rails'
gem 'datagrid'
gem 'doorkeeper', '>= 4.2.0'
gem 'easy_table'
gem 'eco'
gem 'em-websocket'
gem 'enumerize'
gem 'eventmachine', '~> 1.0.4'
gem 'figaro', '0.7.0'
gem 'font-awesome-sass', '4.7.0'
gem 'globalize'
gem 'gon'
gem 'grape', '>= 1.1.0'
gem 'grape-entity', '>= 0.5.2'
gem 'grape-swagger', '>= 0.27.3'
gem 'grape-swagger-ui', '>= 2.2.8'
gem 'hashie', '~> 3.0'
gem 'http_accept_language'
gem 'jbuilder'
gem 'jquery-rails', '~> 4.3.5'
gem 'json'
gem 'kaminari'
gem 'less'
gem 'less-rails'
gem 'liability-proof', '0.0.9'
gem 'yui-compressor'
gem 'mail_form'
gem 'momentjs-rails'
gem 'mobylette', git: 'https://github.com/amarian12/mobylette.git'
gem 'mysql2', '~> 0.4.9'
gem 'nokogiri', '>= 1.8.5'
gem 'omniauth', '>= 1.3.2'
gem 'omniauth-identity'
gem 'omniauth-rails_csrf_protection'
gem 'paper_trail', '~> 4.2.0'
gem 'paranoid2'
gem 'pusher', '~> 0.14.6'
gem 'rack', '~> 1.6.11'
gem 'rack-attack'
gem 'rails'
gem 'rails-i18n'
gem 'rails-observers'
gem 'rails-html-sanitizer', '>= 1.2.0'
gem 'rbtree'
gem 'redis-rails'
gem 'redis-store', '>= 1.4.0'
gem 'responders'
gem 'rest-client', '>= 1.7.3'
gem 'rubyzip', '>= 1.2.1'
gem 'rotp'
gem 'sassc-rails', '>= 2.1.0'
gem 'sass-rails'
gem 'simple_captcha2', require: 'simple_captcha'
gem 'simple_form', '~> 3.5.1'
gem 'simple_form_extension'
gem 'slim-rails'
gem 'sprockets', '>= 2.11.3'
gem 'therubyracer'
gem 'twilio-ruby'
gem 'uglifier'
gem 'unread', git: 'https://github.com/amarian12/unread'
gem 'whenever'
gem 'httparty'
gem 'web3', '~> 0.1.0'

group :development, :test do
  gem 'annotate'
  gem 'factory_bot'
  gem 'faker'
  gem 'barnes'
  gem 'mina'
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'mails_viewer'
  gem 'timecop'
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'byebug'
  gem 'brakeman', :require => false
  gem 'bundler-audit', :require => false
end

group :test do
  gem 'database_cleaner'
  gem 'mocha', :require => false
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'poltergeist'
  gem 'globalize-versioning'
  # rspec-rails rely on test-unit if rails version less then 4.1.0
  # but test-unit has been removed from ruby core since 2.2.0
  gem 'test-unit'
end
